eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5 #间隔5秒钟跳一次（监听有没有服务）
    register-with-eureka: false  #自己不注册自己
  server:
    enable-self-preservation: false #自我保护模式关闭
spring:
  application:
    name: eureka
#server:
#  port: 8761